### ISSUE TITLE
Error after clonning and executing commands

### ISSUE THREAD

**Issue by gustawdaniel** [willbrowningme/nuxt-cockpit-static-blog#1]
```
npm run generate

> new-blog@1.0.0 generate /home/daniel/exp/nuxt-cockpit-static-blog
> nuxt generate

ℹ Production build                                         00:46:14
✔ Builder initialized                                      00:46:14
✔ Nuxt files generated                                     00:46:14

✔ Client
  Compiled successfully in 17.08s

✔ Server
  Compiled successfully in 2.68s


Hash: 540f59f346cf0c0b316d
Version: webpack 4.26.1
Time: 17081ms
Built at: 2019-02-12 00:46:32
                   Asset       Size  Chunks                    Chunk Names
 061446aa9484b808071b.js  693 bytes       3  [emitted]         pages/about
22d2e7bb1d286961b389.css   3.08 KiB       0  [emitted]         app
340f3bd7858a80693898.css  641 bytes       8  [emitted]         vendors.app
 4144c2fb0238aa5eb65c.js    146 KiB       1  [emitted]         commons.app
 5b9908cf79f6a736979d.js   2.27 KiB       7  [emitted]         runtime
 5c17bfdeb03e8ca9201a.js    720 KiB       8  [emitted]  [big]  vendors.app
 798ee25b690aef02a288.js   30.8 KiB       0  [emitted]         app
                LICENSES  547 bytes          [emitted]         
 a56fb7566c5199fc2f07.js   2.26 KiB       5  [emitted]         pages/category/_tag
 c14f2e296c65c449eaf9.js   1.73 KiB       2  [emitted]         pages/_title_slug
 e075d63e6ae61f3c9e01.js   2.08 KiB       6  [emitted]         pages/index
 e23b85522dfa555694b3.js   4.15 KiB       4  [emitted]         pages/blog/_page
 + 3 hidden assets
Entrypoint app = 5b9908cf79f6a736979d.js 4144c2fb0238aa5eb65c.js 340f3bd7858a80693898.css 5c17bfdeb03e8ca9201a.js 22d2e7bb1d286961b389.css 798ee25b690aef02a288.js

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  5c17bfdeb03e8ca9201a.js (720 KiB)

Hash: 09ec27e7422eaabd5646
Version: webpack 4.26.1
Time: 2681ms
Built at: 2019-02-12 00:46:35
             Asset     Size  Chunks             Chunk Names
server-bundle.json  229 KiB          [emitted]  
Entrypoint app = server-bundle.js
ℹ Generating pages                                         00:46:37
✔ Generated /about                                         00:46:37

 ERROR   /                                                 00:46:39

TypeError: Cannot read property '0' of undefined
    at asyncData (46061f11e3abd05e4e44.js:72:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)


 ERROR  Cannot read property '0' of undefined              00:46:39

  at asyncData (46061f11e3abd05e4e44.js:72:22)
  at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by willbrowningme** [comment]
The error is occuring here:

```
if (!data.entries[0]) {
      return error({ message: '404 Page not found', statusCode: 404 })
}
```

You need to make sure you update your .env file to include a valid Cockpit API endpoint.

Keeping the examples shown in .env.example will cause this error.
